#!/bin/sh -e

# Busybox sha256 does not support longopts
sed -e "s/--check/-c/g" -i Makefile.am

mkdir -p patches
for p in *.patch; do
    case $p in
        icedtea-*.patch)
            cp $p patches/
            ;;
        *.patch)
            patch -p1 < "$p"
            ;;
    esac
done

./autogen.sh

# using ccache causes ICEs with pregenerated headers
export CCACHE_DISABLE=1

#export ALT_PARALLEL_COMPILE_JOBS="$(nproc)"
#export HOTSPOT_BUILD_JOBS="$(nproc)"
export JAVA_HOME="/usr/lib/jvm/java-1.5-gcj/"
export PATH="$JAVA_HOME/bin:/usr/share/apache-ant/bin:$PATH"
export DISTRIBUTION_PATCHES=""

# from alpine: disable jvm-breaking optimizations and c++ std
export EXTRA_CPP_FLAGS="$CXXFLAGS -std=gnu++98 -fno-delete-null-pointer-checks -fno-lifetime-dse -fno-strict-overflow"
export EXTRA_CFLAGS="$CFLAGS -std=gnu++98 -Wno-error -fno-delete-null-pointer-checks -fno-lifetime-dse -fno-strict-overflow"

for p in patches/*; do
    case $p in
        icedtea-*.patch)
            export DISTRIBUTION_PATCHES="$DISTRIBUTION_PATCHES $p"
            ;;
    esac
done

jdk_prefix=/usr/lib/jvm/java-1.7-openjdk

for tarball in *.tar.bz2\?no-extract; do
    name="$(echo $tarball | cut -d'.' -f1)"
    case "$name" in
        openjdk)
            src_d="$name.src"
            mkdir -p $src_d
            echo "Extracting $tarball"
            tar xf "$tarball" \
                -C "$src_d" \
                --strip-components=1
            ;;
        *) mv "$tarball" "$name-$2.tar.bz2";;
    esac
done

./configure \
    --prefix="$jdk_prefix" \
    --sysconfdir=/etc \
    --mandir=/usr/share/man \
    --infodir=/usr/share/info \
    --localstatedir=/var \
    --disable-dependency-tracking \
    --disable-downloading \
    --disable-arm32-jit \
    --disable-docs \
    --disable-system-gtk \
    --disable-system-pcsc \
    --disable-system-sctp \
    --without-rhino \
    --with-openjdk-src-dir=$PWD/openjdk.src \
    --with-hotspot-src-zip=$PWD/hotspot-$2.tar.bz2 \
    --with-corba-src-zip=$PWD/corba-$2.tar.bz2 \
    --with-jaxp-src-zip=$PWD/jaxp-$2.tar.bz2 \
    --with-jaxws-src-zip=$PWD/jaxws-$2.tar.bz2 \
    --with-jdk-src-zip=$PWD/jdk-$2.tar.bz2 \
    --with-langtools-src-zip=$PWD/langtools-$2.tar.bz2 \
    --with-jdk-home=$JAVA_HOME

make -j1 icedtea-boot SHELL=/usr/bin/bash
make -j1
echo here
exit 1

mkdir -p "$1/$jdk_prefix"
cp -a openjdk.build-boot/j2sdk-image/* "$1/$jdk_prefix"
cp -a openjdk.build-boot/include       "$1/$jdk_prefix"
rm -rf "$1/$jdk_prefix/src.zip"
rm -rf "$1/usr/lib/bin"
