#!/bin/sh -e

ls -lah

# using ccache causes ICEs with pregenerated headers
export CCACHE_DISABLE=1

#export ALT_PARALLEL_COMPILE_JOBS="$(nproc)"
#export HOTSPOT_BUILD_JOBS="$(nproc)"

export CLASSPATH="/usr/lib/rt.jar:/usr/lib/tools.jar"
export JAVACFLAGS="-cp /usr/lib/rt.jar:/usr/lib/tools.jar"
export JAVA_HOME=/usr

# from alpine: disable jvm-breaking optimizations and c++ std
export EXTRA_CPP_FLAGS="$CXXFLAGS -std=gnu++98 -fno-delete-null-pointer-checks -fno-lifetime-dse -fno-strict-overflow"
export EXTRA_CFLAGS="$CFLAGS -std=gnu++98 -Wno-error -fno-delete-null-pointer-checks -fno-lifetime-dse -fno-strict-overflow"

export CFLAGS="-fcommon"

#TODO: add Void's patches to this package.
for patch in kiss-patches/*; do
    case "$patch" in
        kiss-patches/icedtea-*.patch) DISTRIBUTION_PATCHES="$DISTRIBUTION_PATCHES $patch"
    esac
done

jdk_prefix=/usr/lib/jvm/java-1.7-openjdk

for tarball in *.tar.bz2\?no-extract; do
    src_d="$(echo $tarball | cut -d'.' -f1).src"
    mkdir -p $src_d
    echo "Extracting $tarball"
    tar xf "$tarball" \
        -C "$src_d" \
        --strip-components=1
done

sed -i "/AC_CHECK_HEADERS/s/attr/sys/" acinclude.m4

autoreconf -vif

# FIXME: figure out why this variables need to be set to true.
it_cv_cp39408_javah=true \
    ./configure \
    --prefix="$jdk_prefix" \
    --with-parallel-jobs="$(nproc)" \
    --with-jdk-home=/usr \
    --with-openjdk-src-dir=openjdk.src \
    --with-hotspot-src-dir=hotspot.src \
    --with-corba-src-dir=corba.src \
    --with-jaxp-src-dir=jaxp.src \
    --with-jaxws-src-dir=jaxws.src \
    --with-jdk-src-dir=jdk.src \
    --with-langtools-src-dir=./langtools.src \
    --with-ecj=/usr/bin/javac \
    --with-jdk-home=/usr \
    --with-java=/usr/bin/jamvm \
    --with-jar=/usr/bin/gjar \
    --without-rhino \
    --enable-system-lcms \
    --enable-bootstrap \
    --enable-nss \
    --disable-system-pcsc \
    --disable-downloading \
    --disable-tests \
    --disable-system-sctp \
    --disable-dependency-tracking \
    --disable-downloading \
    --disable-arm32-jit \
    --disable-system-jpeg \
    --disable-system-gtk
# FIXME: figure out why Makefile.in is being removed during the config process.
exit 1
make -j1 SHELL=/usr/bin/bash icedtea-boot

mkdir -p "$1/$jdk_prefix"
cp -a openjdk.build-boot/j2sdk-image/* "$1/$jdk_prefix"
cp -a openjdk.build-boot/include       "$1/$jdk_prefix"
rm -rf "$1/$jdk_prefix/src.zip"
rm -rf "$1/usr/lib/bin"
