#!/bin/sh -e

export CC=clang

: > nostrip # just in case

for patch in *.patch; do
    patch -p1 < $patch
done

JAVAC=/usr/bin/jikes \
    ./configure \
    --prefix=/usr \
    --disable-Werror \
    --disable-gmp \
    --disable-gtk-peer \
    --disable-gconf-peer \
    --disable-plugin \
    --disable-dssi \
    --disable-alsa \
    --disable-gjdoc \
    --disable-examples \
    --with-jikes

make
make install
make install-data
