#!/bin/sh -e

export DESTDIR="$1"

export CC=clang
export CXX=clang++

export CFLAGS="$CFLAGS -w -Wno-implicit-function-declaration -Wno-int-conversion"
export CXXFLAGS="$CXXFLAGS -w -Wno-implicit-function-declaration -Wno-int-conversion"

: > nostrip # just in case

for patch in *.patch; do
    patch -p1 < "$patch"
done

JAVAC=/usr/bin/jikes \
    ./configure \
    --prefix=/usr \
    --disable-Werror \
    --disable-gmp \
    --disable-gtk-peer \
    --disable-gconf-peer \
    --disable-plugin \
    --disable-dssi \
    --disable-alsa \
    --disable-gjdoc \
    --disable-examples \
    --with-jikes

make
make install
make install-data
