#!/bin/sh -e

gcj-6 -Wl,-Bsymbolic -findirect-dispatch -o ecj \
    --main=org.eclipse.jdt.internal.compiler.batch.Main \
    /usr/share/java/ecj.jar -lgcj

JVM_DIR=$1/usr/lib/jvm
JDK_DIR=$JVM_DIR/java-1.5-gcj
JDK_BIN_DIR=$JDK_DIR/bin
JDK_LIB_DIR=$JDK_DIR/lib
JRE_DIR=$JDK_DIR/jre
JRE_BIN_DIR=$JRE_DIR/bin
JRE_LIB_DIR=$JRE_DIR/lib

CPU=$(uname -m | sed -e 's/i.86/i386/g' -e 's/x86_64/amd64/g')

mkdir -p $JDK_BIN_DIR $JDK_LIB_DIR
ln -sf ../../../../bin/gij-6 $JDK_BIN_DIR/java
ln -sf ../../../../bin/fastjar $JDK_BIN_DIR/fastjar
ln -sf ../../../../bin/sinjdoc $JDK_BIN_DIR/javadoc
ln -sf ../../../../bin/grmic-6 $JDK_BIN_DIR/rmic
ln -sf ../../../../bin/gjavah-6 $JDK_BIN_DIR/javah
install -s ecj $JDK_BIN_DIR/javac
ln -sf ../../../../bin/gappletviewer-6 $JDK_BIN_DIR/appletviewer
ln -sf ../../../../bin/gjarsigner-6 $JDK_BIN_DIR/jarsigner
ln -sf ../../../../bin/grmiregistry-6 $JDK_BIN_DIR/rmiregistry
ln -sf ../../../../bin/gkeytool-6 $JDK_BIN_DIR/keytool
ln -sf ../../../../bin/gjar-6 $JDK_BIN_DIR/gjar
ln -sf ../../../../bin/gnative2ascii-6 $JDK_BIN_DIR/gnative2ascii
ln -sf ../../../../share/java/libgcj-tools-6.4.0.jar $JDK_LIB_DIR/tools.jar

mkdir -p $JRE_BIN_DIR $JRE_LIB_DIR/$CPU
ln -sf ../../../../../bin/gij-6 $JRE_BIN_DIR/java
ln -sf ../../../../../bin/grmiregistry-6 $JRE_BIN_DIR/rmiregistry
ln -sf ../../../../../bin/gkeytool-6 $JRE_BIN_DIR/keytool
ln -sf ../../../../../share/java/libgcj-6.4.0.jar $JRE_LIB_DIR/rt.jar
ln -sf ../../../../../../lib/gcj-6-17/libjvm.so $JRE_LIB_DIR/$CPU
ln -sf ../../../../../../lib/gcj-6-17/libjavamath.so $JRE_LIB_DIR/$CPU
ln -sf ../../../../../../lib/gcj-6-17/classmap.db $JRE_LIB_DIR/$CPU
