#!/bin/sh -e

#patch -p1 < fix-jamvm-freeze.patch
sed "s/depends=\"jars,test-jar\"/depends=\"jars\"/" build.xml > _
mv _ build.xml

#export JAVA_HOME="/usr"
export JAVACMD="/usr/bin/jamvm"
export JAVAC="/usr/bin/jikes"
export CLASSPATH="/usr/lib/rt.jar"
export ANT_OPTS="-Dbuild.compiler=jikes -Xnocompact -Xnoinlining"
export BOOTJAVAC_OPTS="-nowarn"

mkdir tmp
export HOME="tmp"
touch tmp/.ant.properties

sh -x bootstrap.sh -Ddist.dir=out #-Dbuild.dir=build
# Current error is with build.xml ; it fails on line 1070 and 558
tree out
false && {
out/bin/ant -Ddist.dir="$1/usr" jars
out/bin/ant -Ddist.dir="$1/usr" dist

mkdir -p "$1/etc/profile.d"
cat <<EOF > $1/etc/profile.d/apache-ant.sh
export PATH=\$PATH:/usr/share/apache-ant/bin
export ANT_HOME=\${ANT_HOME:-/usr/share/apache-ant}
EOF

rm -- $1/usr/bin/*.bat
rm -- $1/usr/bin/*.cmd
}
