#!/bin/sh -e

sed "s/depends=\"jars,test-jar\"/depends=\"jars\"/" build.xml > _
mv _ build.xml

export JAVA_HOME="/usr"
export JAVACMD="/usr/bin/jamvm"
export JAVAC="/usr/bin/jikes"
export CLASSPATH="/usr/lib/rt.jar"
export ANT_OPTS="-Dbuild.compiler=jikes -Xnocompact -Xnoinlining"
export BOOTJAVAC_OPTS="-nowarn"

mkdir tmp
export HOME="tmp"
touch tmp/.ant.properties

sh bootstrap.sh -Ddist.dir=boot

# Use bootstrapped ant to build jars & dist.
boot/bin/ant -Ddist.dir="junk" jars
boot/bin/ant -Ddist.dir="junk" dist

# Remove manuals & Windows stuff.
rm -rf junk/manual
rm -rf junk/bin/*.cmd
rm -rf junk/bin/*.bat

mkdir -p "$1/usr/share/apache-ant"
cp -r junk/* "$1/usr/share/apache-ant"

# Make the new execuatables available in PATH & set ANT_HOME.
mkdir -p   "$1/etc/profile.d"
cat <<EOF > $1/etc/profile.d/apache-ant-bootstrap.sh
#!/bin/sh
export PATH=\$PATH:/usr/share/apache-ant/bin
export ANT_HOME=\${ANT_HOME:-/usr/share/apache-ant}
export JAVA_HOME=\${JAVA_HOME:-/usr}
export JAVACMD="/usr/bin/jamvm"
export JAVAC="/usr/bin/jikes"
export CLASSPATH="/usr/lib/rt.jar"
EOF
