#!/bin/sh -e

for patch in *.patch; do
    patch -p1 < "$patch"
done

./configure \
    --prefix=/usr \
    --sysconfdir=/etc \
    --mandir=/usr/share/man \
    --infodir=/usr/share/info \
    --localstatedir=/var

make
make DESTDIR="$1" install

rm -rf "$1/usr/lib/charset.alias"
rmdir -p "$1/usr/lib" 2> /dev/null || true

# Allow fastjar to be used in place of any other JVM's jar.
if [ -d /usr/lib/jvm/ ]; then
    for d in /usr/lib/jvm/*; do
        mkdir -p "$1$d/bin"
        ln -s /usr/bin/fastjar "$1$d/bin/jar"
    done
fi
