#!/bin/sh -e

sed "s/depends=\"jars,test-jar\"/depends=\"jars\"/" build.xml > _
mv _ build.xml

export JAVA_HOME="${JAVA_HOME:-/usr/lib/jvm/java-1.5-gcj}"
if [ -d "$JAVA_HOME" ]; then
    export JAVACMD="$JAVA_HOME/bin/java"
    export JAVAC="$JAVA_HOME/bin/javac"
else
    export JAVACMD="jamvm"
    export JAVAC="jikes"
fi

mkdir -p tmp
export HOME="tmp"
touch tmp/.ant.properties

sh bootstrap.sh -Ddist.dir=boot

# Remove manuals & Windows stuff.
rm -rf boot/manual
rm -rf boot/bin/*.cmd
rm -rf boot/bin/*.bat

mkdir -p "$1/usr/share/apache-ant"
cp -r boot/* "$1/usr/share/apache-ant"
