#!/bin/sh

baseurl=https://git.alpinelinux.org/aports/plain/community/openjdk8/

curl -s https://git.alpinelinux.org/aports/tree/community/openjdk8?h=master \
    | grep 'patch' \
    | grep href \
    | sed "s/<[^>]*>/<>/g" \
    | cut -d'<' -f6 \
    | tr -d '>' \
    | xargs -I{} sh -c "curl -LO $baseurl{}"
