#!/bin/sh -e

unzip *.zip*
ls -lah

cat <<EOF > manifest
Manifest-Version: 1.0
Main-Class: org.eclipse.jdt.internal.compiler.batch.Main\n
EOF

export CLASSPATH="$(find /usr/share/apache-ant/lib/ -name *.jar | tr '\n' ':'):/usr/lib/rt.jar"

jikes $(find . -type f -name *.java)

fastjar cvfm ecj-bootstrap.jar manifest .

mkdir -p "$1/usr/share/java/"
cp ecj-bootstrap.jar "$1/usr/share/java/"
