#!/bin/sh

bootcp="/usr/share/classpath/tools.zip"
bootcp="$bootcp:/usr/share/classpath/glibj.zip"
bootcp="$bootcp:/usr/share/java/ecj-bootstrap.jar"
bootcp="$bootcp:${CLASSPATH:-/usr/lib/rt.jar}"

source="1.5"
target="1.5"
_cp="."

java="${JAVACMD:-/usr/bin/jamvm}"

args=""

if [ -z $@ ]; then
    printf "javac: no arguments given!\n"
    exit
fi

for arg in $(echo $@ | sed 's/ -/#-/g' | tr '#' '\n' | grep -v -e '^-J' | sed "s/ /#/g"); do
    case $arg in
        -source*)    source="$(echo $arg | cut -d'#' -f2)";;
        -target*)    target="$(echo $arg | cut -d'#' -f2)";;
        -classpath*) bootcp="$bootcp:$(echo $arg | cut -d'#' -f2)";;
        -cp) _cp="$(echo $arg | cut -d'#' -f2)";;
        -bootclasspath*);;
        *) args="$args $(echo $arg | sed 's/#/ /g' )";;
    esac
done

$java \
    -classpath "$bootcp" \
    "org.eclipse.jdt.internal.compiler.batch.Main" \
    -source "$source" \
    -target "$target" \
    -cp "$_cp" \
    -nowarn \
    $args

